#菜单导航
menu:
  home: /
  archives: /archives
  about: /about

#logo
logo: /images/logo.png

#categories-max
categories_max: 5

#tags-max
tags_max: 10

#favicon
favicon: /images/favicon.ico

#ite switch
site_search: true

#rss
rss: /atom.xml

#follow 按顺序展示
follow:
  github: 'https://github.com/shixiaohu2206'
  # facebook: 'https://github.com/shixiaohu2206'
  # twitter: 'https://github.com/shixiaohu2206'
  # instagram: 'https://github.com/shixiaohu2206'
  weixin: 'https://github.com/shixiaohu2206'
  # alipay: 'https://github.com/shixiaohu2206'
  # zhihu: 'https://github.com/shixiaohu2206'
  QQ: 'https://github.com/shixiaohu2206'
  # weibo: 'https://github.com/shixiaohu2206'

#search post url
search_url: /search.xml

#ICP 皖ICP备16021483号-3
site_icp: ''

#友情链接
site_friends:
  房间里的小猫咪: 'http://baidu.com'

#畅言评论
changyan: true

#不蒜子统计
busuanzi: false
