#菜单导航
menu:
  home: /
  archives: /archives
  about: /about
  RSS: /atom.xml

#logo
logo: /images/logo.png

# favicon
favicon: /images/favicon.ico

# site switch
site_search: true

# rss
rss: /atom.xml

# search post url
search_url: /search.xml

#ICP
site_icp: "皖ICP备16021483号-3"

#友情链接
site_friends:
  房间里的小猫咪: "http://baidu.com"
